# Generated by Django 5.1.2 on 2024-11-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_images_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
